### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by byshen** [weehowe-z/electronic-dingtalk#1]
Tried to install following your command, but npm install shows that 
```
npm WARN package.json electronic-dingtalk@1.0.0 No repository field.
```
Could you help?

**Comment by weehowe-z** [comment]
Actually this is a warning for not including `repository` information in `package.json`, which should not cause failure. I've already fixed the warning. 

The only dependency for now is `electron-prebuilt`, you can check whether it has been successfully installed under `node_modules` folder.

**Comment by byshen** [comment]
I think the problem is that I forgot to add `sudo`  before the command. I suggest you to change the command to 
```
sudo npm install && npm start
```

Thanks anyway.

**Comment by weehowe-z** [comment]
Unlike `npm install -g MODULE`, `npm install` will only install modules locally according to `package.json` under current folder.

User privilege  is not required I think.

**Comment by byshen** [comment]
It needs the privilege to create directories under /usr ....
