### ISSUE TITLE
没有看到wechat.js

### ISSUE THREAD

**Issue by hanyou** [weehowe-z/electronic-dingtalk#2]
<script src="wechat.js"></script>在index.html中

**Comment by weehowe-z** [comment]
这个是直接从 [electronic-wechat](https://github.com/geeeeeeeeek/electronic-wechat) 那里搬过来的时候忘记删除了。作者早期引入这个 js 来注入的，不过这边目前只是一个简单的 webview 包装了网页版的应用而已，暂时还没有用到。已经删除～
